travis:
  secure:
    BINSTAR_TOKEN: JC7k00KpSov1/MQR/hHAsMKHn+BU3eNGyRRen/dlnMpJUH5pXuO6JWaH3Kng2wFLDVoXNSyzu5osS6RrAkZp8AAEtVmSzfw5q0ieNryRITaflOU21X63U8YrlIr3mA0k89NRpBMpZIbCIELlajlIfto7mf8X8BWQAITwkpW9N0dPHzM4bCq+gXYy413bKTciG6moqtIeIwnmMqyRhIjT7X9BtDIafQmsX/1mJL+m3P0nhGVsLoRp4uhkbVekJ9q/4xR+BngO4rFYp6d8ODijcCVy5NBpMYDfln2m24iYjzRzWDnD2UDjuUUX0ybwfDXbb0pIFzaZHiq6Sos3wzOtoiFLb/jlkzSUyxzjn/VEHuJbsH2/c3KrX+Un2QalMUwhrjfkFrLYg+7hvI7kG09gry3yeIi/B5A3LjkP2CkkF7P7Uo2j9pvttIKyUVptJRfoYj8SDGZtwEsshg+F8gcVmtlc5W/qkYFcTDR7pBHHBj9D0Qlq9cUrnNuB/ycCcZc/aoQ/rWgMm0YRJMziF1TTdg5g68So/ZkyQ1qrY1xF2a0UuEPxLlNxjrLQExbXIkCpjaA4XdH839Pu5O73m3myHX0wvy08OEQLxpjqNOU+yueEurLip6AGDhnrXqkWK1/DuICu6N52JpFj+W7qdRtAevxFA9Av3ZFx7XbFREn3i+U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
