travis:
  secure:
    BINSTAR_TOKEN: gsME4wQW9SeHIhTsxTLSqGs8tJY0prnd8top8tgfRK0h721RaAJQRpWmt1viP/cO47psDIglqZRryGUpk2N9Vqs6VXYxVIfg8m9sVpkM0I7JY1ySclOx/0LTYL/uvyLrqyt1QIstWCT1eHgm/DH9CQVm9Bq5TxiZfQJC/mH0MwxTRmuqAMH2vR8eZy1tmJwpXXcwZu6A6wtfBCZpTVAWWT0xp8+plcd04c2fLA9B6oUM4T2Djk58cOIPfDDFIKRetApUw6SqNWo8Sz0DQT24rPelCDbh8KBXb490zYG/ASEdZ0/uBbqfMDR8CP+vKkHhg4TuRxQX6zyQIhRuXY7nsZ+vDQH7THSRyN8Q1+tu2KyB4yADNy1hGnfHDLcWu11ObaqDzVl3SLoZhJo3ti2JSq69c5TcHdZPJfs5UCF2E5yYYQ92yqF4oG+9/jq2KcGTrR6dw/q5jbh8oqwSuyoTAQl07Y8NpnAcpI2D7jRW70h5MIAYxfhH7lmZF4nomHDN4yw47LXadQFYonSfZZHfVRb9lXMCwqyMkg+L+H2MFX+JNB0clAnlB9ni9tzC8isuEwrZSuCjHr3R2PkrU78dfPNGDods6aCoULP08J2WDE6Bx8/6itXK6iVJ4jaVMgIEGFOP3SogrD9VZtSOQLBA2Z4jFD92a/RflQgDBvimnFw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
